version: 2

sources:
  - name: bronze
    database: amazon_bi
    schema: bronze
    tables:
      - name: reviews_raw
        description: "Reseñas Amazon crudas — Capa Bronze"

models:
  - name: silver_reviews
    description: "Reseñas Amazon limpias, normalizadas y enriquecidas — Capa Silver"
    columns:
      - name: user_id
        description: "ID único del usuario"
        tests:
          - not_null
      - name: product_id
        description: "ID único del producto (ASIN)"
        tests:
          - not_null
      - name: rating
        description: "Calificación del producto (1.0 a 5.0)"
        tests:
          - not_null
      - name: sentiment
        description: "Sentimiento calculado desde el rating"
        tests:
          - not_null
          - accepted_values:
              values: ['positive', 'neutral', 'negative']
      - name: category
        description: "Categoría del producto"
        tests:
          - not_null
          - accepted_values:
              values: ['Electronics', 'Home_and_Kitchen']
      - name: verified_purchase
        description: "Si la compra fue verificada por Amazon"
        tests:
          - not_null
      - name: event_datetime
        description: "Fecha y hora del evento"
        tests:
          - not_null
      - name: review_year
        description: "Año de la reseña"
        tests:
          - not_null
      - name: review_month
        description: "Mes de la reseña"
        tests:
          - not_null
      - name: avg_product_rating
        description: "Rating promedio del producto calculado desde todas sus reseñas"
        tests:
          - not_null
      - name: total_reviews_product
        description: "Total de reseñas del producto"
        tests:
          - not_null